### ISSUE TITLE
Если в каталоге только одна игра, то её нельзя найти

### ISSUE THREAD

**Issue by ChukharevIlya** [ChukharevIlya/TeamProjectQamid40#1]
# Описание
После добавления в каталог игры, ее нельзя найти, но если к ней добавить еще хотя бы одну, то игра находится.
# Локация дефекта
https://github.com/ChukharevIlya/TeamProjectQamid40/blob/3f70f8b4562c757b0b799cf20030555993ea0858/src/main/java/ru/netology/GameStore.java#L32-L39
# Шаги воспроизведения
1. Открыть [тест](https://github.com/ChukharevIlya/TeamProjectQamid40/blob/player/src/test/java/ru/netology/GameStoreTest.java#L25) в IDEA
2. Запустить тест
3. Посмотреть результат

*Ожидаемый результат:* Программа находит игру game1, добавленную в каталог, и появляется результат true в значении переменной actual.
*Фактический результат:* Программа на нашла игру game1. Значение переменной actual = false.
# Скриншоты
![image](https://user-images.githubusercontent.com/105640778/184338890-1e066692-7963-43c3-ac26-95c7637f5bda.png))
![image](https://user-images.githubusercontent.com/105640778/184339932-701bd40d-0b18-4299-9cf0-1715833c0b64.png)

# Окружение
* **Операционная система:** Windows 7 Домашняя базовая
* **IDE:** IntelliJ IDEA Community Edition 2022.1.2
* **Java:** Open JDK 11
* **Dependency:** Junit5

**Comment by Korartol** [comment]
исправленно
