### ISSUE TITLE
При суммировании времени игрока, проведенного за играми, ответ всегда ноль.

### ISSUE THREAD

**Issue by ChukharevIlya** [ChukharevIlya/TeamProjectQamid40#2]
# Описание
Сумма времени, проведенного за играми, при условии, что играл хотя бы один игрок и хотя бы один раз не может равняться 0. Метод не реализует требования, которые к нему предъявляются, возвращая только ответ 0 в любой ситуации. Метод getSumPlayedTime должен суммировать общее количество времени всех игроков, проведённого за играми этого каталога.
# Локация дефекта
https://github.com/ChukharevIlya/TeamProjectQamid40/blob/18fbc90af3b9575a04675fe8f29867d362ffd90a/src/main/java/ru/netology/GameStore.java#L76-L78
# Шаги воспроизведения
1. Открыть [тест](https://github.com/ChukharevIlya/TeamProjectQamid40/blob/18fbc90af3b9575a04675fe8f29867d362ffd90a/src/test/java/ru/netology/GameStoreTest.java#L142) в IDEA
2. Запустить тест
3. Посмотреть результат

*Ожидаемый результат:* Программа выводит в переменной actual время равное 2, которое игрок провел за игрой.
*Фактический результат:* Программа выдала в переменной actual время равное 0.
# Скриншоты
![image](https://user-images.githubusercontent.com/105640778/184344658-4b54541d-3a9e-4d5e-8feb-fbd74efd0abd.png)
![image](https://user-images.githubusercontent.com/105640778/184344487-6224da82-5e33-4935-8535-5e70d85df23f.png)

# Окружение
* **Операционная система:** Windows 7 Домашняя базовая
* **IDE:** IntelliJ IDEA Community Edition 2022.1.2
* **Java:** Open JDK 11
* **Dependency:** Junit5

**Comment by Korartol** [comment]
Исправленно
