### ISSUE TITLE
Метод не суммирует время проигранное во все игры конкретного жанра игроком, ответ всегда 0

### ISSUE THREAD

**Issue by Korartol** [ChukharevIlya/TeamProjectQamid40#5]
# Описание
Метод не суммирует время проигранное во все игры конкретного жанра игроком, ответ всегда ноль.

# Локация дефекта
https://github.com/ChukharevIlya/TeamProjectQamid40/blob/18fbc90af3b9575a04675fe8f29867d362ffd90a/src/main/java/ru/netology/Player.java#L43-L55

# Шаги воспроизведения
1. Открыть код программы в IDEA
2. Запустить тест с разными данными
3. Посмотреть результат

* Ожидаемый результат - программа суммирует время проигранное игроком в игры одного жанра
* Фактический результат - ответ всегда ноль.

# Скриншот
<img width="767" alt="Снимок экрана 2022-08-15 в 11 12 05" src="https://user-images.githubusercontent.com/102210294/184599966-35ae96bd-c7a0-40fe-83bd-bbac0e59ddcc.png">

# Окружение
* **Операционная система:** MacOS Monterey
* **IDE:** IntelliJ IDEA 2022.1.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by ChukharevIlya** [comment]
При воспроизведении теста обнаружил, что до метода sumGenre не доходит проигранное время, которое должен был зарегистрировать метод play. Метод play изменен https://github.com/ChukharevIlya/TeamProjectQamid40/commit/38cab10796b5f535a6772f8a80cece766096e6c6
